function cost = calculateRouteCost(distance, travelTime, traffic, hazardPenalty, restrictionPenalty, weights)
% CALCULATEROUTECOST Computes weighted composite edge cost for RoutPilot routing.
    cost = weights.distanceWeight * distance + ...
           weights.timeWeight * travelTime + ...
           weights.trafficWeight * traffic + ...
           hazardPenalty + ...
           restrictionPenalty;
end
